name: social_buzz
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  appwrite: ^11.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_hooks: ^0.20.1
  flutter_platform_widgets: ^3.3.5
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  hooks_riverpod: ^2.4.0
  image_picker: ^1.0.4
  json_annotation: ^4.8.1
  logging: ^1.2.0
  lottie: ^2.6.0
  riverpod: ^2.4.0
  timeago: ^3.5.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/gen
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true

  assets:
    enabled: true
    outputs:
      package_generator_enabled: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/imgs/
